#!/usr/bin/env node
/**
 * gen-presets.mjs — generate `packages/bundle-planrun/presets.patch.yml` from
 * `presets/<id>/{preset.yml,plugins.yml}`.
 *
 * DSH reads agent presets only as `@deepseek-ai/dsh-agent-preset` declarations
 * carried by a bundle patch. The legacy `$DSH_HOME/.agent-presets/<id>/`
 * directory format (preset.yml + agent.cordis.yml) is no longer read by any
 * DSH release, so the shipped artifact must be a patch.
 *
 * Usage:
 *   node scripts/gen-presets.mjs           # write the patch
 *   node scripts/gen-presets.mjs --check   # fail when the patch is stale
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..')
const SOURCE_DIR = join(ROOT, 'presets')
const TARGET = join(ROOT, 'packages/bundle-planrun/presets.patch.yml')
const CHECK = process.argv.includes('--check')

/** Indent every non-empty line; blank lines stay blank. */
function indent(text, spaces) {
  const pad = ' '.repeat(spaces)
  return text
    .replace(/\r\n/g, '\n')
    .replace(/\s+$/, '')
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : pad + line))
    .join('\n')
}

function readPreset(dir) {
  const name = dir
  const config = readFileSync(join(SOURCE_DIR, dir, 'preset.yml'), 'utf8')
  const plugins = readFileSync(join(SOURCE_DIR, dir, 'plugins.yml'), 'utf8')
  const id = config.match(/^id:\s*(\S+)\s*$/m)?.[1]
  const order = Number(config.match(/^order:\s*(\d+)\s*$/m)?.[1])
  if (id === undefined) throw new Error(`presets/${name}/preset.yml is missing a top-level "id:"`)
  if (id !== name) throw new Error(`presets/${name}/preset.yml id "${id}" must equal the directory name`)
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id)) throw new Error(`preset id "${id}" is not kebab-case`)
  if (!Number.isInteger(order)) throw new Error(`presets/${name}/preset.yml is missing a top-level "order:"`)
  if (!/^- /m.test(plugins)) throw new Error(`presets/${name}/plugins.yml must be a top-level YAML list`)
  return { id, order, config, plugins }
}

const presets = readdirSync(SOURCE_DIR)
  .filter((entry) => statSync(join(SOURCE_DIR, entry)).isDirectory())
  .map(readPreset)
  .sort((a, b) => a.order - b.order || a.id.localeCompare(b.id))

if (presets.length === 0) throw new Error('no preset directories found under presets/')

const header = [
  '# GENERATED by scripts/gen-presets.mjs — do not edit by hand.',
  '# Source: presets/<id>/{preset.yml,plugins.yml}',
  '# DSH reads agent presets only as `@deepseek-ai/dsh-agent-preset` declarations',
  '# carried by a bundle patch; the legacy $DSH_HOME/.agent-presets directory is dead.',
  '',
].join('\n')

const blocks = presets.map(({ id, config, plugins }) => [
  '- insert:',
  `    - id: preset-${id}`,
  "      name: '@deepseek-ai/dsh-agent-preset'",
  '      config:',
  indent(config, 8),
  '        plugins:',
  indent(plugins, 10),
].join('\n'))

const output = `${header}${blocks.join('\n\n')}\n`

if (CHECK) {
  let current = ''
  try {
    current = readFileSync(TARGET, 'utf8')
  } catch {
    console.error('FAIL: packages/bundle-planrun/presets.patch.yml is missing — run node scripts/gen-presets.mjs')
    process.exit(1)
  }
  if (current !== output) {
    console.error('FAIL: packages/bundle-planrun/presets.patch.yml is stale — run node scripts/gen-presets.mjs')
    process.exit(1)
  }
  console.log(`OK: presets.patch.yml in sync (${presets.map((preset) => preset.id).join(' · ')})`)
  process.exit(0)
}

writeFileSync(TARGET, output)
console.log(`OK: wrote presets.patch.yml (${presets.map((preset) => preset.id).join(' · ')})`)
